/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-23 04:12:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ec/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1654652768084L));
    _jspx_dependants.put("jar:file:/C:/test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ec/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 되는거임!!! tiles 없앨방법 알아보기!!  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	request.setCharacterEncoding("utf-8");

      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("  <title>Document</title>\n");
      out.write("  \n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300&display=swap\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\n");
      out.write(" <!-- Bootstrap CSS,js -->\n");
      out.write("<script\n");
      out.write("   src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("   integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\n");
      out.write("   crossorigin=\"anonymous\"></script>\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\n");
      out.write("<link\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("   rel=\"stylesheet\"\n");
      out.write("   integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("   crossorigin=\"anonymous\">\n");
      out.write(" <link href=\"css/styles.css\" rel=\"stylesheet\" />\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("	*{\n");
      out.write("      transition-duration: 0.8s;\n");
      out.write("    }\n");
      out.write("    body{\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("    }\n");
      out.write("    div{\n");
      out.write("      width: 100%;\n");
      out.write("/*       height: 100vh;\n");
      out.write("      font-size: 32px; \n");
      out.write("      text-align: center; */\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    img {\n");
      out.write("	max-height:969px;\n");
      out.write("	min-width:100%;  /* 1900  */\n");
      out.write("} \n");
      out.write("\n");
      out.write("\n");
      out.write(".togglebtn {\n");
      out.write("	position: absolute;\n");
      out.write("	right:50px;\n");
      out.write("	top:10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("    \n");
      out.write("    /* 먹거리, 먹플리 버튼  */\n");
      out.write("    #eat {\n");
      out.write("	position: absolute;\n");
      out.write("	left:380px;\n");
      out.write("	top:650px;\n");
      out.write("	}\n");
      out.write("	#eatlist {\n");
      out.write("	position: absolute;\n");
      out.write("	left:550px;\n");
      out.write("	top:650px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("/* 	/*회원가입, 로그인(내정보, 찜), 카테고리,커뮤니티,예약조회  */\n");
      out.write("/* 	.section ul {\n");
      out.write("	list-style:none;\n");
      out.write("	color:white;\n");
      out.write(" 	position: absolute;\n");
      out.write("	right:380px;\n");
      out.write("	top:50px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.section ul li {\n");
      out.write("	float:left;\n");
      out.write("	} */\n");
      out.write("\n");
      out.write("	 /* 볼거리, 볼플리 버튼  */\n");
      out.write("    #see {\n");
      out.write("	position: absolute;\n");
      out.write("	left:1050px;\n");
      out.write("	top:1380px;\n");
      out.write("	}\n");
      out.write("	#seelist {\n");
      out.write("	position: absolute;\n");
      out.write("	left:1220px;\n");
      out.write("	top:1380px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	/* 풋터버튼 */\n");
      out.write("	#footer1 {\n");
      out.write("	position: absolute;\n");
      out.write("	left:100px;\n");
      out.write("	top:2000px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#footer2 {\n");
      out.write("	position: absolute;\n");
      out.write("	left:280px;\n");
      out.write("	top:2000px;\n");
      out.write("	}\n");
      out.write("	#footer3 {\n");
      out.write("	position: absolute;\n");
      out.write("	left:90px;\n");
      out.write("	top:2080px;\n");
      out.write("	}\n");
      out.write("	#footer4 {\n");
      out.write("	position: absolute;\n");
      out.write("	left:280px;\n");
      out.write("	top:2080px;\n");
      out.write("	} \n");
      out.write("	\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("<script>\n");
      out.write("	$(function(){\n");
      out.write("		$(\"html, body\").animate({ scrollTop: 0 }, \"slow\"); \n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* When the user clicks on the button,\n");
      out.write("	toggle between hiding and showing the dropdown content */\n");
      out.write("	function myFunction() {\n");
      out.write("	    document.getElementById(\"myDropdown\").classList.toggle(\"show\");\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	// Close the dropdown menu if the user clicks outside of it\n");
      out.write("	window.onclick = function(event) {\n");
      out.write("	  if (!event.target.matches('.dropbtn')) {\n");
      out.write("\n");
      out.write("	    var dropdowns = document.getElementsByClassName(\"dropdown-content\");\n");
      out.write("	    var i;\n");
      out.write("	    for (i = 0; i < dropdowns.length; i++) {\n");
      out.write("	      var openDropdown = dropdowns[i];\n");
      out.write("	      if (openDropdown.classList.contains('show')) {\n");
      out.write("	        openDropdown.classList.remove('show');\n");
      out.write("	      }\n");
      out.write("	    }\n");
      out.write("	  }\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("  \n");
      out.write("  \n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write(" window.onload = function(){\n");
      out.write("     const elm = document.querySelectorAll('.section');\n");
      out.write("     const elmCount = elm.length;\n");
      out.write("     elm.forEach(function(item, index){\n");
      out.write("       item.addEventListener('mousewheel', function(event){\n");
      out.write("         event.preventDefault();\n");
      out.write("         let delta = 0;\n");
      out.write("\n");
      out.write("         if (!event) event = window.event;\n");
      out.write("         if (event.wheelDelta) {\n");
      out.write("             delta = event.wheelDelta / 120;\n");
      out.write("             if (window.opera) delta = -delta;\n");
      out.write("         } \n");
      out.write("         else if (event.detail)\n");
      out.write("             delta = -event.detail / 3;\n");
      out.write("\n");
      out.write("         let moveTop = window.scrollY;\n");
      out.write("         let elmSelector = elm[index];\n");
      out.write("\n");
      out.write("         // wheel down : move to next section\n");
      out.write("         if (delta < 0){\n");
      out.write("           if (elmSelector !== elmCount-1){\n");
      out.write("             try{\n");
      out.write("               moveTop = window.pageYOffset + elmSelector.nextElementSibling.getBoundingClientRect().top;\n");
      out.write("             }catch(e){}\n");
      out.write("           }\n");
      out.write("         }\n");
      out.write("         // wheel up : move to previous section\n");
      out.write("         else{\n");
      out.write("           if (elmSelector !== 0){\n");
      out.write("             try{\n");
      out.write("               moveTop = window.pageYOffset + elmSelector.previousElementSibling.getBoundingClientRect().top;\n");
      out.write("             }catch(e){}\n");
      out.write("           }\n");
      out.write("         }\n");
      out.write("\n");
      out.write("         const body = document.querySelector('html');\n");
      out.write("         window.scrollTo({top:moveTop, left:0, behavior:'smooth'});\n");
      out.write("       });\n");
      out.write("     });\n");
      out.write("   }\n");
      out.write(" </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" style=\"display: none;\">\n");
      out.write("  <symbol id=\"bootstrap\" viewBox=\"0 0 118 94\">\n");
      out.write("    <title>Bootstrap</title>\n");
      out.write("    <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z\"></path>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"home\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"speedometer2\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z\"/>\n");
      out.write("    <path fill-rule=\"evenodd\" d=\"M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"table\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"people-circle\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\"/>\n");
      out.write("    <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"grid\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"collection\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M2.5 3.5a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-11zm2-2a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6v7zm1.5.5A.5.5 0 0 1 1 13V6a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"calendar3\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z\"/>\n");
      out.write("    <path d=\"M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"chat-quote-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM7.194 6.766a1.688 1.688 0 0 0-.227-.272 1.467 1.467 0 0 0-.469-.324l-.008-.004A1.785 1.785 0 0 0 5.734 6C4.776 6 4 6.746 4 7.667c0 .92.776 1.666 1.734 1.666.343 0 .662-.095.931-.26-.137.389-.39.804-.81 1.22a.405.405 0 0 0 .011.59c.173.16.447.155.614-.01 1.334-1.329 1.37-2.758.941-3.706a2.461 2.461 0 0 0-.227-.4zM11 9.073c-.136.389-.39.804-.81 1.22a.405.405 0 0 0 .012.59c.172.16.446.155.613-.01 1.334-1.329 1.37-2.758.942-3.706a2.466 2.466 0 0 0-.228-.4 1.686 1.686 0 0 0-.227-.273 1.466 1.466 0 0 0-.469-.324l-.008-.004A1.785 1.785 0 0 0 10.07 6c-.957 0-1.734.746-1.734 1.667 0 .92.777 1.666 1.734 1.666.343 0 .662-.095.931-.26z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"cpu-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M6.5 6a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z\"/>\n");
      out.write("    <path d=\"M5.5.5a.5.5 0 0 0-1 0V2A2.5 2.5 0 0 0 2 4.5H.5a.5.5 0 0 0 0 1H2v1H.5a.5.5 0 0 0 0 1H2v1H.5a.5.5 0 0 0 0 1H2v1H.5a.5.5 0 0 0 0 1H2A2.5 2.5 0 0 0 4.5 14v1.5a.5.5 0 0 0 1 0V14h1v1.5a.5.5 0 0 0 1 0V14h1v1.5a.5.5 0 0 0 1 0V14h1v1.5a.5.5 0 0 0 1 0V14a2.5 2.5 0 0 0 2.5-2.5h1.5a.5.5 0 0 0 0-1H14v-1h1.5a.5.5 0 0 0 0-1H14v-1h1.5a.5.5 0 0 0 0-1H14v-1h1.5a.5.5 0 0 0 0-1H14A2.5 2.5 0 0 0 11.5 2V.5a.5.5 0 0 0-1 0V2h-1V.5a.5.5 0 0 0-1 0V2h-1V.5a.5.5 0 0 0-1 0V2h-1V.5zm1 4.5h3A1.5 1.5 0 0 1 11 6.5v3A1.5 1.5 0 0 1 9.5 11h-3A1.5 1.5 0 0 1 5 9.5v-3A1.5 1.5 0 0 1 6.5 5z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"gear-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"speedometer\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M8 2a.5.5 0 0 1 .5.5V4a.5.5 0 0 1-1 0V2.5A.5.5 0 0 1 8 2zM3.732 3.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 8a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 8zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 7.31A.91.91 0 1 0 8.85 8.569l3.434-4.297a.389.389 0 0 0-.029-.518z\"/>\n");
      out.write("    <path fill-rule=\"evenodd\" d=\"M6.664 15.889A8 8 0 1 1 9.336.11a8 8 0 0 1-2.672 15.78zm-4.665-4.283A11.945 11.945 0 0 1 8 10c2.186 0 4.236.585 6.001 1.606a7 7 0 1 0-12.002 0z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"toggles2\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M9.465 10H12a2 2 0 1 1 0 4H9.465c.34-.588.535-1.271.535-2 0-.729-.195-1.412-.535-2z\"/>\n");
      out.write("    <path d=\"M6 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 1a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm.535-10a3.975 3.975 0 0 1-.409-1H4a1 1 0 0 1 0-2h2.126c.091-.355.23-.69.41-1H4a2 2 0 1 0 0 4h2.535z\"/>\n");
      out.write("    <path d=\"M14 4a4 4 0 1 1-8 0 4 4 0 0 1 8 0z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"tools\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path d=\"M1 0L0 1l2.2 3.081a1 1 0 0 0 .815.419h.07a1 1 0 0 1 .708.293l2.675 2.675-2.617 2.654A3.003 3.003 0 0 0 0 13a3 3 0 1 0 5.878-.851l2.654-2.617.968.968-.305.914a1 1 0 0 0 .242 1.023l3.356 3.356a1 1 0 0 0 1.414 0l1.586-1.586a1 1 0 0 0 0-1.414l-3.356-3.356a1 1 0 0 0-1.023-.242L10.5 9.5l-.96-.96 2.68-2.643A3.005 3.005 0 0 0 16 3c0-.269-.035-.53-.102-.777l-2.14 2.141L12 4l-.364-1.757L13.777.102a3 3 0 0 0-3.675 3.68L7.462 6.46 4.793 3.793a1 1 0 0 1-.293-.707v-.071a1 1 0 0 0-.419-.814L1 0zm9.646 10.646a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708zM3 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026L3 11z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"chevron-right\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path fill-rule=\"evenodd\" d=\"M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z\"/>\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"geo-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path fill-rule=\"evenodd\" d=\"M4 4a4 4 0 1 1 4.5 3.969V13.5a.5.5 0 0 1-1 0V7.97A4 4 0 0 1 4 3.999zm2.493 8.574a.5.5 0 0 1-.411.575c-.712.118-1.28.295-1.655.493a1.319 1.319 0 0 0-.37.265.301.301 0 0 0-.057.09V14l.002.008a.147.147 0 0 0 .016.033.617.617 0 0 0 .145.15c.165.13.435.27.813.395.751.25 1.82.414 3.024.414s2.273-.163 3.024-.414c.378-.126.648-.265.813-.395a.619.619 0 0 0 .146-.15.148.148 0 0 0 .015-.033L12 14v-.004a.301.301 0 0 0-.057-.09 1.318 1.318 0 0 0-.37-.264c-.376-.198-.943-.375-1.655-.493a.5.5 0 1 1 .164-.986c.77.127 1.452.328 1.957.594C12.5 13 13 13.4 13 14c0 .426-.26.752-.544.977-.29.228-.68.413-1.116.558-.878.293-2.059.465-3.34.465-1.281 0-2.462-.172-3.34-.465-.436-.145-.826-.33-1.116-.558C3.26 14.752 3 14.426 3 14c0-.599.5-1 .961-1.243.505-.266 1.187-.467 1.957-.594a.5.5 0 0 1 .575.411z\"/>\n");
      out.write("  </symbol>\n");
      out.write("\n");
      out.write("</svg>\n");
      out.write("  <div class=\"section\" >\n");
      out.write("	 <img alt=\"배경\" src=\"image/main_eat.png\">\n");
      out.write("<nav class=\"navbar navbar-dark fixed-top\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <button class=\"navbar-toggler togglebtn\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasNavbar\" aria-controls=\"offcanvasNavbar\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("   </div>\n");
      out.write("    \n");
      out.write("    <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasNavbar\" aria-labelledby=\"offcanvasNavbarLabel\">\n");
      out.write("      <div class=\"offcanvas-header\">\n");
      out.write("      	<h5 class=\"offcanvas-title\" id=\"offcanvasNavbarLabel\">\n");
      out.write("      	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write(" <br></h5>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\n");
      out.write("      </div>\n");
      out.write("      <hr id=\"sidehr\">\n");
      out.write("      <div class=\"offcanvas-body\">\n");
      out.write("        <ul class=\"nav nav-pills flex-column mb-auto\"\">\n");
      out.write("      <li>\n");
      out.write("            \n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/memberForm_main.do\" class=\"nav-link nav-hover\"> <!-- aria-current=\"page\" -->\n");
      out.write("          <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"/></svg>\n");
      out.write("          회원가입\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("      \n");
      out.write("      ");
      out.write("\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      <!-- 로그인시 나타나는 항목 -->\n");
      out.write("      <li>\n");
      out.write("        <a href=\"#\" class=\"nav-link nav-hover\">\n");
      out.write("          <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"/></svg>\n");
      out.write("          내 정보\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category.do\" class=\"nav-link nav-hover\">\n");
      out.write("          <span class=\"bi pe-none me-2\" width=\"16\" height=\"16\">📷</span>\n");
      out.write("          <!-- <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#collection\"/></svg> -->\n");
      out.write("          Category\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"#\" class=\"nav-link nav-hover\">\n");
      out.write("          <span class=\"bi pe-none me-2\" width=\"16\" height=\"16\">💬</span>\n");
      out.write("          <!-- <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#chat-quote-fill\"/></svg> -->\n");
      out.write("          Community\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"#\" class=\"nav-link nav-hover\">\n");
      out.write("          <span class=\"bi pe-none me-2\" width=\"16\" height=\"16\">📣</span>\n");
      out.write("          <!-- <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#geo-fill\"/></svg> -->\n");
      out.write("          Event\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <a href=\"#\" class=\"nav-link nav-hover\">\n");
      out.write("          <span class=\"bi pe-none me-2\" width=\"16\" height=\"16\">❤</span>\n");
      out.write("          <!-- <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\">❤</svg> -->\n");
      out.write("          찜\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("      <!-- 로그인시 나타나는 항목-e  -->\n");
      out.write("      \n");
      out.write("      <li>\n");
      out.write("        <a href=\"#\" class=\"nav-link nav-hover\">\n");
      out.write("          <span class=\"bi pe-none me-2\" width=\"16\" height=\"16\">📅</span>\n");
      out.write("          <!-- <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#calendar3\"/></svg> -->\n");
      out.write("          예약조회\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("\n");
      out.write("      <li>\n");
      out.write("        <a href=\"#\" class=\"nav-link link-dark\">\n");
      out.write("          <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#grid\"/></svg>\n");
      out.write("          <b>최근 본 즐길거리</b><br><br>\n");
      out.write("          < \n");
      out.write("          <img src=\"image/dog.jpg\" width=\"50px\" height=\"50px\" /> >\n");
      out.write("        </a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("	<!--  <ul>\n");
      out.write("	 	<li></li>\n");
      out.write("	 	<li>\n");
      out.write("	 		<a class=\"ulhover\" id=\"hover1\"><img src=\"image/icon_e03.png\" alt=\"회원가입\" width=\"30px\" height=\"30px\">\n");
      out.write("				<span class=\"tooltiptext tooltip-bottom\">회원가입</span>\n");
      out.write("			</a>\n");
      out.write("	 	</li>\n");
      out.write("	 	<li>\n");
      out.write("	 		<a class=\"ulhover\" id=\"hover2\"><img src=\"image/icon_e03.png\" alt=\"로그인\" width=\"30px\" height=\"30px\">\n");
      out.write("				<span class=\"tooltiptext tooltip-bottom2\">로그인</span>\n");
      out.write("			</a>\n");
      out.write("		</li>\n");
      out.write("	 	<li>\n");
      out.write("	 		 <a class=\"ulhover\" id=\"hover3\"><img src=\"image/icon_e03.png\" alt=\"로그인\" width=\"30px\" height=\"30px\">\n");
      out.write("				<span class=\"tooltiptext tooltip-bottom3\">내정보</span>\n");
      out.write("			</a>\n");
      out.write("	 	</li>\n");
      out.write("	 	<li>\n");
      out.write("	 		 <a class=\"ulhover\" id=\"hover4\"><img src=\"image/icon_e03.png\" alt=\"로그인\" width=\"30px\" height=\"30px\">\n");
      out.write("				<span class=\"tooltiptext tooltip-bottom4\">찜</span>\n");
      out.write("			</a>\n");
      out.write("	 	</li>\n");
      out.write("	 	<li>\n");
      out.write("	 		 <a class=\"ulhover\" id=\"hover5\"><img src=\"image/icon_e03.png\" alt=\"로그인\" width=\"30px\" height=\"30px\">\n");
      out.write("				<span class=\"tooltiptext tooltip-bottom5\">예약조회</span>\n");
      out.write("			</a>\n");
      out.write("	 	</li>\n");
      out.write("	 	<li>\n");
      out.write("			Example single danger button\n");
      out.write("			<div class=\"btn-group\">\n");
      out.write("			  <button type=\"button\" class=\"btn btn-danger dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("			    Action\n");
      out.write("			  </button>\n");
      out.write("			  <ul class=\"dropdown-menu\">\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n");
      out.write("			    <li><hr class=\"dropdown-divider\"></li>\n");
      out.write("			    <li><a class=\"dropdown-item\" href=\"#\">Separated link</a></li>\n");
      out.write("			  </ul>\n");
      out.write("			</div>\n");
      out.write("	 	</li>\n");
      out.write("	 </ul>\n");
      out.write("	 <a href=\"#\" id=\"signup\"><img src=\"image/icon_1.png\" alt=\"회원가입\" width=\"155px\" height=\"66px\"></a> -->\n");
      out.write("	<a href=\"#\" id=\"eat\"><img src=\"image/icon_1.png\" alt=\"먹거리\" width=\"155px\" height=\"66px\"></a>\n");
      out.write("	<a href=\"#\" id=\"eatlist\"><img src=\"image/icon_11.png\" alt=\"먹플리\" width=\"155px\" height=\"66px\"></a>\n");
      out.write("	  \n");
      out.write("  </div>\n");
      out.write("  <div class=\"section\">\n");
      out.write("  	<img alt=\"배경\" src=\"image/main_see.png\" >\n");
      out.write("	  <a href=\"#\" id=\"see\"><img src=\"image/icon_2.png\" alt=\"볼거리\" width=\"155px\" height=\"66px\"></a>\n");
      out.write("	  <a href=\"#\" id=\"seelist\"><img src=\"image/icon_12.png\" alt=\"볼플리\" width=\"155px\" height=\"66px\"></a>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"section\">\n");
      out.write("  	<img alt=\"배경\" src=\"image/main_footer.png\">\n");
      out.write("  	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do\" id=\"footer1\"><img src=\"image/footer1.png\" alt=\"먹고보자\" width=\"150px\" height=\"50px\"></a>\n");
      out.write("  	<a href=\"#\" id=\"footer2\"><img src=\"image/footer2.png\" alt=\"먹보사장님광장\" width=\"205px\" height=\"50px\"></a>\n");
      out.write("  	<a href=\"#\" id=\"footer3\"><img src=\"image/footer3.png\" alt=\"먹보 상담소\" width=\"180px\" height=\"50px\"></a>\n");
      out.write("  	<a href=\"#\" id=\"footer4\"><img src=\"image/footer4.png\" alt=\"먹보소식\" width=\"150px\" height=\"50px\"></a>\n");
      out.write("  	\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main.jsp(13,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/main.jsp(13,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(13,2) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("      	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("       	");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("       	");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/main.jsp(269,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLogOn == true && member !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("      		<h4>환영합니다 <br>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.user_nick }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님!</h4>\n");
          out.write("        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/user/logout.do\" class=\"nav-link nav-hover\">\n");
          out.write("          <svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"/></svg>\n");
          out.write("          로그아웃\n");
          out.write("        </a>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("       	<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/user/loginForm.do \" class=\"nav-link nav-hover\">\n");
          out.write("       		<svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"/></svg>\n");
          out.write("          로그인\n");
          out.write("       	</a>\n");
          out.write("       	");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
